$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: phi-3-mini-4k-trtllm-1
endpoint_name: phi-3-mini-4k-nim-endpoint-aml-1
environment: 
  name: phi-3-mini-4k-env
  image: saurabharegistry.azurecr.io/phi-3-mini-4k:latest
  inference_config:
      liveness_route:
          path: /v1/health/ready
          port: 8000
      readiness_route:
          path: /v1/health/ready
          port: 8000
      scoring_route:
          path: /
          port: 8000
instance_type: Standard_NC24ads_A100_v4
instance_count: 1
request_settings:
    max_concurrent_requests_per_instance: 256
    request_timeout_ms: 180000
environment_variables:
    NGC_API_KEY: ${{azureml://connections/ngc/credentials/NGC_API_KEY}}
    shm-size: 16GB
    gpus: all
    OMPI_ALLOW_RUN_AS_ROOT: 1
    OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
    # NIM_LOW_MEMORY_MODE: 1
    NIM_MANIFEST_ALLOW_UNSAFE: 1
    NIM_MODEL_PROFILE: tensorrt_llm-a100-fp16-tp1-throughput
liveness_probe:
    timeout: 300
    period: 300
    failure_threshold: 100
readiness_probe:
    timeout: 300
    period: 300
    failure_threshold: 100
